# Generated by Django 4.1.2 on 2023-04-19 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cathsu_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='baptism',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='confirmation',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='cur_level',
            field=models.CharField(choices=[('high_school', 'high_school'), ('vocation', 'vocation'), ('tetiary', 'tetiary')], default='100', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='home_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='institution',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('other', 'other')], default='single', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='pro_pic',
            field=models.ImageField(default='profile.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='member',
            name='res_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
